# Assignment 4:  Recommendation systems

Here we'll implement a content-based recommendation algorithm.

In [218]:
import math
import numpy as np
from scipy.sparse import csr_matrix, lil_matrix
from sklearn.feature_extraction.text import CountVectorizer

In [219]:
movie_names = ['Avatar', 'Get Shorty', 'Princess Bride', 'Goonies']
movie_descriptions = [
    'an epic science fiction film',
    'a crime thriller comedy film; adapted from a book',
    'a fantasy comedy adventure film; adapted from a book',
    'an adventure comedy film'
]
# ratings: row=user, col=movie
# All ratings are between 0 and 1, with 1 meaning the user really liked the movie.
# A 0 value means the user has not rated the movie.
ratings = csr_matrix([
    [.1, 0, .2, 0],
    [0, .9, 0, .3],
    [.3, 0, .9, 0],
    [0, 0, 0, .4],
    [0, 0, .3, .4]
    ])
print ratings

  (0, 0)	0.1
  (0, 2)	0.2
  (1, 1)	0.9
  (1, 3)	0.3
  (2, 0)	0.3
  (2, 2)	0.9
  (3, 3)	0.4
  (4, 2)	0.3
  (4, 3)	0.4


In [220]:
# Do not modify.
vectorizer = CountVectorizer(token_pattern=r'(?u)\b\w+\b', dtype=np.float)
movie_term_matrix = vectorizer.fit_transform(movie_descriptions)
vocabulary = np.array(vectorizer.get_feature_names())
print('movie_term_matrix:')
print(movie_term_matrix.todense())
print('vocabulary')
print(vocabulary)
# movie_term_matrix: value i,j is the frequency of term j in the description of movie i.

movie_term_matrix:
[[ 0.  0.  0.  1.  0.  0.  0.  1.  0.  1.  1.  0.  1.  0.]
 [ 2.  1.  0.  0.  1.  1.  1.  0.  0.  0.  1.  1.  0.  1.]
 [ 2.  1.  1.  0.  1.  1.  0.  0.  1.  0.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.]]
vocabulary
[u'a' u'adapted' u'adventure' u'an' u'book' u'comedy' u'crime' u'epic'
 u'fantasy' u'fiction' u'film' u'from' u'science' u'thriller']


In [221]:
def document_frequencies(movie_term_matrix):
    """ Compute the number of different documents that each term appears in.
    Params:
      movie_term_matrix...csr_matrix where entry i,j is the number
                          of times term j appears in document i
    Returns:
      a numpy array with one element per term in the vocabulary."""
    
    rows, columns = movie_term_matrix.shape
    dfs = np.zeros(columns)
    for row in range(rows):
        term_index = movie_term_matrix[row].nonzero()[1]
        for index in term_index:
            dfs[index] = dfs[index] + 1 
    return dfs
    
    
dfs = document_frequencies(movie_term_matrix)
dfs

array([ 2.,  2.,  2.,  2.,  2.,  3.,  1.,  1.,  1.,  1.,  4.,  2.,  1.,  1.])

In [222]:
def tfidf(movie_term_matrix, dfs):
    """ Create a new matrix that transforms movie_term_matrix using tfidf.
    Simply divide each value by the document frequency for that term.
    
    Params:
      movie_term_matrix...csr_matrix where entry i,j is the number
                          of times term j appears in document i
      dfs.................document frequencies for each term.
    Returns:
      A csr_matrix that is a copy of movie_term_matrix where value
      i,j is divided by the document frequency of term j"""
    copy_csr = movie_term_matrix.copy()
    rows, cols = movie_term_matrix.shape
    for row in range(rows):
        for col in range(cols):
            copy_csr[[row],[col]] = copy_csr[[row],[col]]/(1. * dfs[col])
    return copy_csr

# tfidf matrix: row=movie, col=term
tfidf_matrix = tfidf(movie_term_matrix, dfs)
tfidf_matrix.todense()

matrix([[ 0.        ,  0.        ,  0.        ,  0.5       ,  0.        ,
          0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
          0.25      ,  0.        ,  1.        ,  0.        ],
        [ 1.        ,  0.5       ,  0.        ,  0.        ,  0.5       ,
          0.33333333,  1.        ,  0.        ,  0.        ,  0.        ,
          0.25      ,  0.5       ,  0.        ,  1.        ],
        [ 1.        ,  0.5       ,  0.5       ,  0.        ,  0.5       ,
          0.33333333,  0.        ,  0.        ,  1.        ,  0.        ,
          0.25      ,  0.5       ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.5       ,  0.5       ,  0.        ,
          0.33333333,  0.        ,  0.        ,  0.        ,  0.        ,
          0.25      ,  0.        ,  0.        ,  0.        ]])

In [223]:
def make_user_profiles(ratings, tfidf_matrix):
    """
    Create a user profile matrix by computing the weighted average of the tfidf
    vectors of each movie he has rated. E.g., if a person has rated 
    one movie .2 with tfidf vector ([.1, .3]) and rated another movie
    .6 with tfidf vector([.2, .4]), then the weighted average is:
    [(.2*.1 + .6*.2) / (.2 + .6), (.2*.3 + .6*.4) / (.2 + .6)]
    Params:
      ratings........the user/movie ratings matrix
      tfidf_matrix...the movie/term tfidf matrix
    Returns:
      A csr matrix where each row represents a user and the columns represent terms.
    """
    #used for shapes of the matrix constructed below
    users, movies = ratings.shape
    movie, terms = tfidf_matrix.shape
    
    #initialize a 2D matrix
    two_d_matrix = np.zeros(shape=(users, terms))
    
    #convert CSR matrix to array for row+row addition
    tfidf_array = tfidf_matrix.toarray()
    
    #constructing the user profile for each user
    for user in range(users):
        array_zero = np.zeros(terms)
        non_zero = ratings[user].nonzero()[1]
        temp = np.zeros(terms, dtype=np.float)
        movie_rating = iter(ratings[user].data)           #get the user rating for a movie
        for nz in non_zero:
            temp +=  tfidf_array[nz]*next(movie_rating)   #column wise sum of two rows
        total_rating = np.sum(ratings[user].data, axis=0)
        two_d_matrix[[user]] = temp / total_rating        #entire row divided by total user rating of all movies
    return csr_matrix(two_d_matrix)    

user_profiles = make_user_profiles(ratings, tfidf_matrix)
user_profiles.todense()

matrix([[ 0.66666667,  0.33333333,  0.33333333,  0.16666667,  0.33333333,
          0.22222222,  0.        ,  0.33333333,  0.66666667,  0.33333333,
          0.25      ,  0.33333333,  0.33333333,  0.        ],
        [ 0.75      ,  0.375     ,  0.125     ,  0.125     ,  0.375     ,
          0.33333333,  0.75      ,  0.        ,  0.        ,  0.        ,
          0.25      ,  0.375     ,  0.        ,  0.75      ],
        [ 0.75      ,  0.375     ,  0.375     ,  0.125     ,  0.375     ,
          0.25      ,  0.        ,  0.25      ,  0.75      ,  0.25      ,
          0.25      ,  0.375     ,  0.25      ,  0.        ],
        [ 0.        ,  0.        ,  0.5       ,  0.5       ,  0.        ,
          0.33333333,  0.        ,  0.        ,  0.        ,  0.        ,
          0.25      ,  0.        ,  0.        ,  0.        ],
        [ 0.42857143,  0.21428571,  0.5       ,  0.28571429,  0.21428571,
          0.33333333,  0.        ,  0.        ,  0.42857143,  0.        ,
          0.

Next, we'll predict a user's rating based on the cosine similarity between the user's profile and the item's tfidf vector.

In [224]:
def norm(vector):
    """
    Compute the Euclidean norm of one row of a csr_matrix.
    https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm
    Input:
      vector...one row from a csr_matrix
    Returns:
      a float, the Euclidean norm of the vector.
    """
    to_array = vector.toarray()
    return np.sqrt(np.sum(np.square(to_array)))
    
norm(csr_matrix([3,4]))

5.0

In [225]:
def cosine(v1, v2):
    """
    Compute the cosine similarity between two vectors (rows from a csr_matrix).
    https://en.wikipedia.org/wiki/Cosine_similarity
    Params:
      v1...one vector
      v2...another vector
    Returns:
      a float representing the cosine similarity/
    """
    v1_array = v1.toarray()[0]
    v2_array = v2.toarray()[0]
    numerator = v1_array.dot(v2_array)
    denominator = norm(v1) * norm(v2)
    return numerator / (1. * denominator)

round(cosine(csr_matrix([2,4]), csr_matrix([3,8])), 5)

0.99451

In [227]:
def predict_ratings_w_user_profiles(ratings, user_profiles, tfidf_matrix):
    """
    Make a copy of the ratings matrix. Replace each 0 entry with a predicted score
    based on user_profile. Specifically, the ratings of user i for movie j is the 
    cosine similarity between user i's profile and movie's j tfidf vector.
    
    Params:
      ratings.........the user x movie ratings matrix.
      user_profiles...the user x term profile matrix
      tfidf_matrix....the move x term tfidf matrix
    Returns:
      a user x movie csr_matrix of ratings. It should be a copy of the original
      ratings matrix, where 0 values have been replaced by the prediced rating.
    """
    copy_ratings = ratings.copy()
    to_array = copy_ratings.toarray()
    
    for user in range(len(to_array)):
        row = to_array[user]
        for movie in range(len(row)):
            col = row[movie]
            if to_array[user][movie] == 0:
                #print user, movie
                #print user_profiles.toarray()[user], tfidf_matrix.toarray()[movie]
                #to_array[user][movie] = cosine(user_profiles.toarray()[user], tfidf_matrix.toarray()[movie])
                to_array[user][movie] = cosine(user_profiles[user], tfidf_matrix[movie])
    return csr_matrix(to_array)
predicted = predict_ratings_w_user_profiles(ratings, user_profiles, tfidf_matrix)
predicted.todense()

matrix([[ 0.1       ,  0.48953468,  0.2       ,  0.35045309],
        [ 0.04514693,  0.9       ,  0.57142822,  0.3       ],
        [ 0.3       ,  0.51857187,  0.9       ,  0.33970573],
        [ 0.20920278,  0.10678984,  0.28972493,  0.4       ],
        [ 0.11225271,  0.46388588,  0.3       ,  0.4       ]])

In [228]:
import json

def doround(x):
    return ['%.3f' % i for i in x]

outf = open('output.txt', 'wt')
json.dump(
    {
        'dfs': doround(document_frequencies(movie_term_matrix).tolist()),
        'tfidf': doround(tfidf(movie_term_matrix, dfs).todense().A1),
        'profiles': doround(make_user_profiles(ratings, tfidf(movie_term_matrix, dfs)).todense().A1),
        'norm': round(norm(csr_matrix([5,6])), 2),
        'cosine': round(cosine(csr_matrix([5,6]), csr_matrix([-5,-1])), 2),
        'predicted': doround(predict_ratings_w_user_profiles(ratings,
                                                     make_user_profiles(ratings, tfidf(movie_term_matrix, dfs)),
                                                     tfidf(movie_term_matrix, dfs)).todense().A1),
    },
    outf, indent=2, sort_keys=True)
outf.close()
    